### ISSUE TITLE
Can we rename this repo?

### ISSUE THREAD

**Issue by bnolan** [janusvr/janusvr-issues#2]
/janusvr/janusvr-issues/issues seems a bit redundant. ;)

**Comment by sirkitree** [comment]
I'm modeling it after what backdrop does

* github.com/backdrop/backdrop
* github.com/backdrop/backdrop-issues

Open to suggestions though. I don't wanna do a lot of work until James is 100% on board. Cuz if he doesn't use this, there is no point in it.

**Comment by bnolan** [comment]
Sweet, look good to me.
